### ISSUE TITLE
[NIO] Multiple save(on:)'s the same Request fail to complete, spin-lock, hang process

### ISSUE THREAD

**Issue by jseibert** [vapor/mysql#143]
** On the nio branch only. 100% reproducible. Works on master.

Attempting to create and save multiple model instances on the same Request (or on the same db connection at boot) never completes, and the process hangs while burning all available CPU.

Here's the simplest repro case:

```swift
public func boot(_ app: Application) throws {
    _ = app.withConnection(to: .mysql) { (db) -> Future<Void> in
        let cat1 = TransactionCategory(name: "Category 1")
        let cat2 = TransactionCategory(name: "Category 2")
    
        return [
            cat1.save(on: db),
            cat2.save(on: db)
        ].map(to: Void.self, on: db) { results in
            print("CREATED THE CATEGORIES")
            print(results)

            return Void()
        }
    }
}
```

Obviously, any simple model will work. The print() lines never execute.

If one of the save(on:) lines is commented out, everything works as expected. 

Upon digging in, the issue lies at MySQL/MySQLPacketDecoder.swift:220. Once session.connectionState gets set to .columnsDone, it never gets set to anything else and no bytes are ever read, because that switch case is a no-op.  The method returns .continue, which causes NIO/Codec.swift:112 to spin infinitely. 

Here are verbose outputs (which a couple additional custom print lines) of saving multiple (2) or single (1) record at a time. You'll see at the end of multiple.txt that it falls into .columnsDone whereas the single case never does.

[multiple.txt](https://github.com/vapor/mysql/files/1830024/multiple.txt)
[single.txt](https://github.com/vapor/mysql/files/1830025/single.txt)

**Comment by tanner0101** [comment]
This has to do with pipelining. This lib _should_ support it, but the messy MySQL wire protocol is going to make that a huge pain. Probably easiest if the connection waits for the previous query to be done before continuing. 

If you do `.save()` and flatMap being doing the next save, it should work fine.

**Comment by mcdappdev** [comment]
Does that make it more inefficient if it has to wait to do the next query?

**Comment by tanner0101** [comment]
I don't think there will be a noticeable difference. Pipelining can be a performance boost if you optimize for it, but it's also possible it could be a performance drain. To properly pipeline you need someway to identify the multiplexed streams. Generating and validating those identifiers could require extra work. 

In the Postgres driver it was possible to avoid this altogether by ensuring that both `query` and `simpleQuery` only consisted of one send/recv (thus pipelining works great with Postgres). However, from what I can tell MySQL _requires_ two steps for a parameterized query as you must know the statement ID to send an execute packet. That means we would need to actually de-multiplex the stream and yeah.. huge pain. I think the overhead and complexity introduced by doing that would outweigh any real benefits gained.

**Comment by tanner0101** [comment]
(See the above commit where this has been fixed and a new test is added)

**Comment by mcdappdev** [comment]
👍

**Comment by jseibert** [comment]
👍

**Comment by jseibert** [comment]
@tanner0101 This is NOT fixed for me on RC2. The same test code above now fails with:

```
error(⚠️ MySQL Error: Prepare response has invalid status
- id: MySQLError.prepareStatus

File: /Users/jseibert/api/.build/checkouts/mysql.git-1890032512239690518/Sources/MySQL/Protocol/MySQLComStmtPrepareOK.swift
 - func: init(bytes:)
 - line: 25
 - column: 133
)
```

**Comment by jseibert** [comment]
The status byte it receives is 1 rather than 0.

**Comment by tanner0101** [comment]
Closing in favor of vapor/fluent#411

**Comment by tanner0101** [comment]
Re-opening again since there's actually two issues going on here. Related, but different.

For MySQL, the problem is that if two queries are activated while one query is in progress, when the current query finishes it will then activate the two awaiting queries at the exact same moment. 

The waiting needs to be chained instead.
