### ISSUE TITLE
TimeZone extension causes crash on Linux

### ISSUE THREAD

**Issue by DrewHood** [vapor/mysql#97]
Hi there, 

I've found an issue in the latest release of vapor/mysql. In `Bind.swift`, around line 250, there is this extension to [Foundation's TimeZone](https://developer.apple.com/reference/foundation/timezone).

```
extension TimeZone {
    static let utc = TimeZone(abbreviation: "UTC")!
}

```
When running this code on Ubuntu 16.04, I'm encountering a crash for unwrapping a nil Optional. It appears that some (possibly all? I've only confirmed this in docker ubuntu 16.04) Linux instances are unable to recognize the "UTC" abbreviation. 

*Impact Scope*
In my testing, this makes all DB writes to mysql fail on Ubuntu 16.04. Read operations work for me.

I have only tested on Ubuntu 16.04 inside a docker container (`ubuntu:16.04` image to be exact). I have not tested to see if there is some library that could be installed to mitigate this, but I haven't found anything in the Foundation docs to indicate that this should be needed. 

*Repro Steps*
```
import Foundation

extension TimeZone {
static let utc = TimeZone(secondsFromGMT: 0)!
}

let utc = TimeZone.utc
```

Compile/run this code using swiftc on Ubuntu 16.04. 

*Fix*
In my testing, I'm able to workaround this by changing that code to a different initializer: 

```
static let utc = TimeZone(secondsFromGMT: 0)!
```

However, I don't suggest this as the actual fix because it still uses force-unwrapping, which we really shouldn't be doing. Ideally, the package should account for the possibility of `TimeZone.init` returning `nil`, as all Apple's currently documented initializers can do so.

**Comment by natebird** [comment]
We encountered the same issue on the PostgreSQL stack. The issue is related to not having the `tzdata` package not installed. See https://github.com/vapor-community/postgresql/issues/43#issuecomment-302916926

It was resolved by not relying on `tzdata` in PR https://github.com/vapor-community/postgresql/pull/44. I think the solution above works just as well.

**Comment by DrewHood** [comment]
Thanks. I'll leave changing the code to other community members. Installing the `tzdata` package does fix the issue for me. For what it's worth, as a Vapor user, installing that package is negligible overhead for me. Perhaps just documenting that dependency somewhere would be enough. Though I still don't feel right about force-unwrapping.

**Comment by LoganWright** [comment]
@DrewHood can you confirm whether or not the timezone:0 works? If so, that would seem like an apt solution to me. Any chance you could submit a PR?

**Comment by DrewHood** [comment]
It happened to work for me in this instance, but I don't know how it will behave on different systems. I think the long-term solution here is to have the framework account for the possibility of a `nil` `TimeZone`. Unfortunately I don't have time in my schedule right now to write the tests for a PR for this.

**Comment by LoganWright** [comment]
@DrewHood unfortunately, that would be a breaking change, and I think we need a way to reliably create a timezone. For now, I think introducing the 0 is an appropriate solution given the constraints of the package. I'll submit a PR and see how it runs on our tests.

**Comment by LoganWright** [comment]
I was wrong, it's all internal, so no breaking changes ... updated and merged 👍
